## FIRST LINE/ROW: Info & Status
# First param ─┌
[username]
format = " [╭─$user]($style)@"
show_always = true
style_root = "bold red"
style_user = "bold cyan"

# Second param
[hostname]
disabled = false
format = "[$hostname]($style) in "
ssh_only = false
style = "bold cyan"
#trim_at = "-"

# Third param
[directory]
style = "cyan"
truncate_to_repo = true
truncation_length = 0
truncation_symbol = "repo: "

# Fourth param
[sudo]
disabled = false

# Before all the version info (python, nodejs, php, etc.)
[git_status]
ahead = "⇡${count}"
behind = "⇣${count}"
deleted = "x"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
style = "white"

# Last param in the first line/row
[cmd_duration]
disabled = false
format = "took [$duration]($style)"
min_time = 1
style = "bold cyan"

## SECOND LINE/ROW: Prompt
# Somethere at the beginning
[battery]
charging_symbol = ""
disabled = true
discharging_symbol = ""
full_symbol = ""

[[battery.display]]  # "bold red" style when capacity is between 0% and 10%
disabled = false
style = "bold red"
threshold = 15

[[battery.display]]  # "bold yellow" style when capacity is between 10% and 30%
disabled = true
style = "bold yellow"
threshold = 50

[[battery.display]]  # "bold green" style when capacity is between 10% and 30%
disabled = true
style = "bold green"
threshold = 80

# Prompt: optional param 1
[time]
disabled = false
format = "[ ├ $time]($style)\n"
style = "bold cyan"
time_format = "%T"

# Prompt: param 2
[character]
error_symbol = " [×](bold red)"
success_symbol = " [╰─λ](bold cyan)"

# SYMBOLS
[status]
disabled = false
format = '[\[$symbol$status_common_meaning$status_signal_name$status_maybe_int\]]($style)'
map_symbol = true
pipestatus = true
symbol = "🔴"

[aws]
symbol = " "

[conda]
symbol = " "

[dart]
symbol = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[os]
#disabled = false
style = "bg:color_os fg:color_foreground_dark"
#format = '[$symbol(v$version)(  $edition)(  $codename)(  $type)]($style)[](bg:color_background_base fg:color_os)'
## uncomment the format above for all available information and comment out the line below
## format = '[$symbol]($style)[](bg:color_background_base fg:color_os)'
## other variables:
##   name = The current operating system name
##   type = The current operating system type
##   codename = The current operating system codename, if applicable
##   edition = The current operating system edition, if applicable
##   version = The current operating system version, if applicable

[os.symbols]
Alpaquita = " " # nf-fa-bell
Alpine = " " # nf-linux-alpine
Amazon = " " # nf-fa-amazon
Android = " " # nf-dev-android
Arch = " " # nf-linux-archlinux
Artix = " " # nf-linux-artix
CentOS = " " # nf-linux-centos
Debian = " " # nf-linux-debian
DragonFly = " " # nf-fae-butterfly
Emscripten = " " # nf-fa-toggle_on
EndeavourOS = " " # nf-linux-endeavour
Fedora = " " # nf-linux-fedora
FreeBSD = " " # nf-linux-freebsd
Garuda = "󰛓 " # nf-md-feather
Gentoo = " " # nf-linux-gentoo
HardenedBSD = "󰔇  " # nf-md-tennis_ball
Illumos = " " # nf-linux-illumos
Linux = " " # nf-linux-tux
Mabox = "󰆦  " # nf-fa-cube
Macos = " " # nf-linux-apple
Manjaro = " " # nf-linux-manjaro
Mariner = " " # nf-fa-life_saver
MidnightBSD = " " # nf-fa-moon_o
Mint = "󰣭  " # nf-md-linux_mint
NetBSD = " " # nf-fa-flag
NixOS = " " # nf-linux-nixos
OpenBSD = " " # nf-linux-openbsd
OpenCloudOS = " " # nf-fa-cloud
openEuler = "󰏒  " # nf-md-owl
openSUSE = " " # nf-linux-opensuse
OracleLinux = "󰌷  " # nf-md-link
Pop = " " # nf-linux-pop_os
Raspbian = " " # nf-linux-raspberry_pi
Redhat = "󱄛 " # nf-md-redhat
RedHatEnterprise = " " # nf-linux-redhat
Redox = "󰀘  " # nf-md-orbit
Solus = " " # nf-linux-solus
SUSE = " " # nf-linux-opensuse
Ubuntu = " " # nf-linux-ubuntu
Unknown = " " # nf-fa-question_circle
Windows = " " # nf-fa-windows

[package]
symbol = " "

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[swift]
symbol = "ﯣ "
